name: deploy test-deploy
on: [push]
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: appleboy/ssh-action@v0.1.7
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{ secrets.SSH_PWD }}  
                script: |
                    ls -al
                    touch test.txt
                    echo "hello imooc" >> test.txt
                    cat test.txt

            